/* Hebrew and Arabic texts. Each row: English (as written in the code), Hebrew, Arabic. */
const TR: [string, string, string][] = [
  // — header, home, general —
  ['Paper Archive', 'ארכיון נייר', 'أرشيف الورق'],
  ['Language', 'שפה', 'اللغة'],
  ['Privacy', 'פרטיות', 'الخصوصية'],
  ['On this device', 'במכשיר הזה', 'على هذا الجهاز'],
  ['Local processing', 'עיבוד מקומי', 'معالجة محلية'],
  ['Close', 'סגירה', 'إغلاق'],
  ['Back', 'חזרה', 'رجوع'],
  ['Cancel', 'ביטול', 'إلغاء'],
  ['Save', 'שמירה', 'حفظ'],
  ['Delete', 'מחיקה', 'حذف'],
  ['Open', 'פתיחה', 'فتح'],
  ['Done', 'סיום', 'تم'],
  ['Later', 'אחר כך', 'لاحقًا'],
  ['Ready', 'מוכן', 'جاهز'],
  ['Turn a pile of paper into a searchable archive.', 'הופכים ערימת ניירות לארכיון שאפשר לחפש בו.', 'حوِّل كومة من الأوراق إلى أرشيف قابل للبحث.'],
  ['Prop your phone above the table and go through your papers one by one. Each page is captured on its own the moment it lies still. No photos to take, nothing to crop or rename.', 'מציבים את הטלפון מעל השולחן ועוברים על הניירות אחד אחד. כל דף נקלט מעצמו ברגע שהוא מונח בלי לזוז. אין צורך לצלם, לחתוך או לשנות שמות.', 'ثبّت هاتفك فوق الطاولة ومرّر أوراقك واحدة تلو الأخرى. تُلتقط كل صفحة تلقائيًا لحظة استقرارها. لا حاجة لالتقاط صور أو قصّ أو إعادة تسمية.'],
  ['Processed locally on your device.', 'מעובד מקומית במכשיר שלך.', 'تتم المعالجة محليًا على جهازك.'],
  ['Your documents stay on this device. No account, no upload.', 'המסמכים שלך נשארים במכשיר הזה. בלי חשבון, בלי העלאה.', 'تبقى مستنداتك على هذا الجهاز. بلا حساب وبلا رفع.'],
  ['Start archiving', 'התחלת סריקה', 'ابدأ الأرشفة'],
  ['Start a new archive', 'ארכיון חדש', 'أرشيف جديد'],
  ['See how it works', 'איך זה עובד', 'كيف يعمل'],
  ['Nobody presses a button here. A page goes down, the outline locks on, and it is captured.', 'אף אחד לא לוחץ כאן על כפתור. דף מונח, המסגרת ננעלת עליו, והוא נקלט.', 'لا أحد يضغط على زر هنا. توضع الصفحة، يثبت الإطار عليها، فتُلتقط.'],
  ['Prototype with sample documents ·', 'אב־טיפוס עם מסמכים לדוגמה ·', 'نموذج أولي بمستندات تجريبية ·'],
  ['Open a sample archive', 'פתיחת ארכיון לדוגמה', 'افتح أرشيفًا تجريبيًا'],
  ['About & terms', 'אודות ותנאים', 'حول التطبيق والشروط'],
  ['About and terms', 'אודות ותנאים', 'حول التطبيق والشروط'],
  ['About Paper Archive', 'אודות ארכיון נייר', 'حول أرشيف الورق'],
  ['I understand', 'הבנתי', 'فهمت'],
  // — how it works —
  ['How it works', 'איך זה עובד', 'كيف يعمل'],
  ['Usual scanner apps', 'אפליקציות סריקה רגילות', 'تطبيقات المسح المعتادة'],
  ['Tap → photograph → crop → rename → file it', 'לוחצים ← מצלמים ← חותכים ← משנים שם ← מתייקים', 'اضغط ← صوّر ← قصّ ← أعد التسمية ← احفظ'],
  ['…then repeat for every page in the pile.', '…ואז חוזרים על זה לכל דף בערימה.', '…ثم كرّر ذلك لكل صفحة في الكومة.'],
  ['Pick up a paper, open it, put it down. Next.', 'מרימים נייר, פותחים, מניחים. הבא.', 'التقط ورقة، افتحها، ضعها. التالية.'],
  ['The app captures, separates and sorts while you keep going.', 'האפליקציה קולטת, מפרידה וממיינת בזמן שאתם ממשיכים.', 'يلتقط التطبيق ويفصل ويفرز بينما تواصل أنت.'],
  ['What happens on your device', 'מה קורה במכשיר שלך', 'ما يحدث على جهازك'],
  ['The camera watches the table', 'המצלמה צופה בשולחן', 'الكاميرا تراقب الطاولة'],
  ['Your phone rests above the table, looking down. No handling, no aiming.', 'הטלפון מונח מעל השולחן ומביט למטה. בלי להחזיק ובלי לכוון.', 'يستقر هاتفك فوق الطاولة متجهًا إلى الأسفل. بلا إمساك وبلا توجيه.'],
  ['A new paper appears', 'נייר חדש מופיע', 'تظهر ورقة جديدة'],
  ['When you lay something down, its outline is found in the camera picture.', 'כשמניחים משהו, קווי המתאר שלו מזוהים בתמונת המצלמה.', 'عندما تضع شيئًا، يُعثر على حدوده في صورة الكاميرا.'],
  ['It is captured when still', 'הוא נקלט כשהוא לא זז', 'تُلتقط عندما تستقر'],
  ['Once the page stops moving for a moment, it is captured and flattened.', 'ברגע שהדף מפסיק לזוז לרגע, הוא נקלט ומיושר.', 'بمجرد أن تتوقف الصفحة عن الحركة للحظة، تُلتقط وتُسوّى.'],
  ['The text is read', 'הטקסט נקרא', 'يُقرأ النص'],
  ['Hebrew and English text is read from each page, on this device.', 'טקסט בעברית ובאנגלית נקרא מכל דף, במכשיר הזה.', 'يُقرأ النص العبري والإنجليزي من كل صفحة، على هذا الجهاز.'],
  ['Pages are grouped', 'הדפים מקובצים', 'تُجمع الصفحات'],
  ['Page 2 of a bill is attached to page 1, so each document stays whole.', 'עמוד 2 של חשבון מצורף לעמוד 1, כך שכל מסמך נשאר שלם.', 'تُلحق الصفحة 2 من الفاتورة بالصفحة 1، فيبقى كل مستند كاملًا.'],
  ['Everything is sorted', 'הכול ממוין', 'يُفرز كل شيء'],
  ['Sender, date and amount are detected. Look-alikes are flagged for you.', 'השולח, התאריך והסכום מזוהים. מסמכים דומים מסומנים בשבילך.', 'يُكتشف المرسل والتاريخ والمبلغ. وتُعلَّم المستندات المتشابهة لك.'],
  // — setup —
  ['Place your phone above the table', 'הציבו את הטלפון מעל השולחן', 'ضع هاتفك فوق الطاولة'],
  ['Put your phone somewhere with a clear view of the table.', 'הניחו את הטלפון במקום שרואה היטב את השולחן.', 'ضع هاتفك في مكان يرى الطاولة بوضوح.'],
  ['Open and place each document on the table.', 'פתחו והניחו כל מסמך על השולחן.', 'افتح كل مستند وضعه على الطاولة.'],
  ['Keep moving — the app captures documents automatically.', 'המשיכו הלאה — האפליקציה קולטת את המסמכים לבד.', 'استمر — يلتقط التطبيق المستندات تلقائيًا.'],
  ['Camera', 'מצלמה', 'الكاميرا'],
  ['Simulated desk', 'שולחן מדומה', 'طاولة محاكاة'],
  ['Sample pile, for trying the flow', 'ערימה לדוגמה, כדי לנסות', 'كومة تجريبية لتجربة الخطوات'],
  ['This device’s camera', 'המצלמה של המכשיר', 'كاميرا هذا الجهاز'],
  ['Falls back to the simulated desk if unavailable', 'אם אינה זמינה, יופעל השולחן המדומה', 'إن لم تتوفر، تُستخدم الطاولة المحاكاة'],
  ['Start camera', 'הפעלת מצלמה', 'تشغيل الكاميرا'],
  ['Camera frames are analyzed in this browser and never leave the device.', 'תמונות המצלמה מנותחות בדפדפן הזה ולעולם לא יוצאות מהמכשיר.', 'تُحلَّل لقطات الكاميرا في هذا المتصفح ولا تغادر الجهاز أبدًا.'],
  ['Keep the whole table in view. Leave room for the pile on one side.', 'שמרו על כל השולחן בתמונה. השאירו מקום לערימה בצד אחד.', 'أبقِ الطاولة كلها في الإطار. واترك مكانًا للكومة في جانب واحد.'],
  ['Table in view', 'השולחן בתמונה', 'الطاولة في الإطار'],
  // — camera —
  ['Archiving', 'בסריקה', 'جارٍ الأرشفة'],
  ['Paused', 'מושהה', 'متوقف مؤقتًا'],
  ['Pause', 'השהיה', 'إيقاف مؤقت'],
  ['Resume', 'המשך', 'استئناف'],
  ['Light', 'פנס', 'الإضاءة'],
  ['Demo speed', 'מהירות הדגמה', 'سرعة العرض'],
  ['Finish archive', 'סיום', 'إنهاء الأرشفة'],
  ['Start over', 'התחלה מחדש', 'البدء من جديد'],
  ['Start over?', 'להתחיל מחדש?', 'البدء من جديد؟'],
  ['Keep going', 'להמשיך', 'متابعة'],
  ['Leave and go back to the start screen', 'יציאה וחזרה למסך הפתיחה', 'الخروج والعودة إلى شاشة البداية'],
  ['Leave for now. Your pages are saved', 'לצאת בינתיים. הדפים שלך נשמרו', 'اخرج الآن. صفحاتك محفوظة'],
  ['Captured pages are kept on this device.', 'הדפים שנקלטו נשמרים במכשיר הזה.', 'تُحفظ الصفحات الملتقطة على هذا الجهاز.'],
  ['Nothing has been captured yet.', 'עדיין לא נקלט דבר.', 'لم يُلتقط شيء بعد.'],
  ['The session restarts from the first document.', 'הסריקה תתחיל מחדש מהמסמך הראשון.', 'ستبدأ الجلسة من جديد من المستند الأول.'],
  ['The {0} captured so far will be discarded.', '{0} שנקלטו עד עכשיו יימחקו.', 'سيتم تجاهل {0} الملتقطة حتى الآن.'],
  ['The {0} not yet sorted will be discarded. Documents already in this archive stay.', '{0} שעוד לא מוינו יימחקו. מסמכים שכבר בארכיון יישארו.', 'سيتم تجاهل {0} غير المفروزة بعد. المستندات الموجودة في هذا الأرشيف ستبقى.'],
  ['That was the whole pile', 'זו הייתה כל הערימה', 'كانت هذه الكومة كلها'],
  ['Live camera. Detection is simulated in this prototype.', 'מצלמה חיה. הזיהוי מדומה באב־הטיפוס הזה.', 'كاميرا مباشرة. الاكتشاف محاكى في هذا النموذج.'],
  ['Current page', 'הדף הנוכחי', 'الصفحة الحالية'],
  ['Captured pages', 'דפים שנקלטו', 'الصفحات الملتقطة'],
  ['Captured page {0}', 'דף {0} שנקלט', 'الصفحة الملتقطة {0}'],
  ['Waiting for the next document', 'ממתין למסמך הבא', 'بانتظار المستند التالي'],
  ['Something new on the table', 'משהו חדש על השולחן', 'شيء جديد على الطاولة'],
  ['Document detected', 'זוהה מסמך', 'تم اكتشاف مستند'],
  ['Hold still…', 'לא לזוז…', 'ثبّت الورقة…'],
  ['Focusing…', 'ממקד…', 'جارٍ التركيز…'],
  ['Captured', 'נקלט', 'تم الالتقاط'],
  ['New page detected', 'זוהה דף חדש', 'تم اكتشاف صفحة جديدة'],
  ['Saved. Place the next one', 'נשמר. הניחו את הבא', 'تم الحفظ. ضع التالي'],
  ['Pile finished', 'הערימה הסתיימה', 'انتهت الكومة'],
  ['Place a document on the table', 'הניחו מסמך על השולחן', 'ضع مستندًا على الطاولة'],
  ['Captured. Place the next page', 'נקלט. הניחו את הדף הבא', 'تم الالتقاط. ضع الصفحة التالية'],
  ['Captured, a little soft. Keep it still for a sharper copy', 'נקלט, קצת מטושטש. השאירו אותו במקום לעותק חד יותר', 'تم الالتقاط بوضوح أقل. أبقها ثابتة للحصول على نسخة أوضح'],
  [' · page {0} of {1}', ' · עמוד {0} מתוך {1}', ' · الصفحة {0} من {1}'],
  ['Detected', 'זוהה', 'مُكتشف'],
  ['Holding still', 'יציב', 'ثابت'],
  ['In focus', 'בפוקוס', 'واضح'],
  ['Saved', 'נשמר', 'محفوظ'],
  ['No buttons to press. Lay a document down and let go.', 'אין על מה ללחוץ. מניחים מסמך ומשחררים.', 'لا أزرار للضغط. ضع مستندًا واتركه.'],
  ['Not detecting? A table darker than the paper works best.', 'לא מזהה? שולחן כהה מהנייר עובד הכי טוב.', 'لا يتم الاكتشاف؟ طاولة أغمق من الورق تعمل بشكل أفضل.'],
  ['Capture the view now', 'לקלוט את התמונה עכשיו', 'التقط المشهد الآن'],
  ['That page was already scanned. It will be marked as a possible duplicate.', 'הדף הזה כבר נסרק. הוא יסומן ככפילות אפשרית.', 'تم مسح هذه الصفحة من قبل. ستُعلَّم كنسخة مكررة محتملة.'],
  ['Looks like a page you already scanned', 'נראה כמו דף שכבר סרקת', 'تبدو كصفحة مسحتها من قبل'],
  ['Continuing your archive. Place the next document.', 'ממשיכים בארכיון שלך. הניחו את המסמך הבא.', 'متابعة أرشيفك. ضع المستند التالي.'],
  ['Continuing “{0}”. Place the next document.', 'ממשיכים ב„{0}”. הניחו את המסמך הבא.', 'متابعة «{0}». ضع المستند التالي.'],
  ['Retaking page {0} of “{1}”. Lay the page down and hold still.', 'צילום מחדש של עמוד {0} ב„{1}”. הניחו את הדף ואל תזיזו.', 'إعادة التقاط الصفحة {0} من «{1}». ضع الصفحة وثبّتها.'],
  ['Adding pages to “{0}”. Lay each page down, then tap Done.', 'מוסיפים דפים ל„{0}”. הניחו כל דף, ובסוף הקישו סיום.', 'إضافة صفحات إلى «{0}». ضع كل صفحة ثم اضغط تم.'],
  ['read while you work', 'נקראים תוך כדי עבודה', 'تُقرأ أثناء عملك'],
  ['{0} read so far', '{0} נקראו עד עכשיו', 'قُرئ {0} حتى الآن'],
  // — processing —
  ['Building your archive', 'בונים את הארכיון', 'جارٍ إنشاء أرشيفك'],
  ['Running on this device. You can put your phone down.', 'רץ במכשיר הזה. אפשר להניח את הטלפון.', 'يعمل على هذا الجهاز. يمكنك وضع هاتفك جانبًا.'],
  ['Reading your pages on this device. The text reader is downloaded once; your pages are never uploaded.', 'קוראים את הדפים במכשיר הזה. קורא הטקסט יורד פעם אחת בלבד; הדפים שלך לעולם לא מועלים.', 'تُقرأ صفحاتك على هذا الجهاز. يُنزَّل قارئ النص مرة واحدة فقط؛ ولا تُرفع صفحاتك أبدًا.'],
  ['Your archive is ready', 'הארכיון מוכן', 'أرشيفك جاهز'],
  ['No pages were captured, so the sample pile was used.', 'לא נקלטו דפים, ולכן נעשה שימוש בערימה לדוגמה.', 'لم تُلتقط أي صفحات، لذا استُخدمت الكومة التجريبية.'],
  ['Documents detected', 'זוהו מסמכים', 'المستندات المكتشفة'],
  ['Pages separated', 'הדפים הופרדו', 'فُصلت الصفحات'],
  ['Text extracted', 'הטקסט חולץ', 'استُخرج النص'],
  ['Documents classified', 'המסמכים מוינו', 'صُنّفت المستندات'],
  ['Duplicates checked', 'נבדקו כפילויות', 'تم فحص النسخ المكررة'],
  ['Archive created', 'הארכיון נוצר', 'تم إنشاء الأرشيف'],
  ['Saved on this device', 'נשמר במכשיר הזה', 'محفوظ على هذا الجهاز'],
  ['{0} captured', '{0} נקלטו', 'التُقط {0}'],
  ['{0} of {1} pages', '{0} מתוך {1} עמודים', '{0} من {1} صفحات'],
  ['{0} of {1}', '{0} מתוך {1}', '{0} من {1}'],
  ['Text reader unavailable, pages kept as images', 'קורא הטקסט לא זמין, הדפים נשמרו כתמונות', 'قارئ النص غير متاح، حُفظت الصفحات كصور'],
  ['Documents', 'מסמכים', 'المستندات'],
  ['Pages', 'עמודים', 'الصفحات'],
  ['Categories', 'קטגוריות', 'الفئات'],
  ['Possible duplicates', 'כפילויות אפשריות', 'نسخ مكررة محتملة'],
  ['Need review', 'לבדיקה', 'تحتاج مراجعة'],
  ['View archive', 'לארכיון', 'عرض الأرشيف'],
  ['0 bytes uploaded. Every step above ran in this browser.', '0 בייטים הועלו. כל השלבים רצו בדפדפן הזה.', 'لم يُرفع أي بايت. كل الخطوات جرت في هذا المتصفح.'],
  ['0 bytes of your documents uploaded. Every step ran in this browser.', '0 בייטים מהמסמכים שלך הועלו. כל השלבים רצו בדפדפן הזה.', 'لم يُرفع أي بايت من مستنداتك. كل الخطوات جرت في هذا المتصفح.'],
  // — archive & documents —
  ['My Archive', 'הארכיון שלי', 'أرشيفي'],
  [' · saved on this device', ' · נשמר במכשיר הזה', ' · محفوظ على هذا الجهاز'],
  [' · sample, not saved', ' · דוגמה, לא נשמר', ' · تجريبي، غير محفوظ'],
  ['Scan more documents', 'סריקת מסמכים נוספים', 'مسح مستندات أخرى'],
  ['All archives', 'כל הארכיונים', 'كل الأرشيفات'],
  ['Archive sections', 'אזורי הארכיון', 'أقسام الأرشيف'],
  ['Needs review', 'לבדיקה', 'تحتاج مراجعة'],
  ['Export', 'ייצוא', 'تصدير'],
  ['Search documents...', 'חיפוש מסמכים...', 'ابحث في المستندات...'],
  ['Clear search', 'ניקוי חיפוש', 'مسح البحث'],
  ['Try', 'נסו', 'جرّب'],
  ['· searches the text inside every page', '· מחפש בטקסט שבתוך כל דף', '· يبحث في النص داخل كل صفحة'],
  ['Filter', 'סינון', 'تصفية'],
  ['All', 'הכול', 'الكل'],
  ['Add category', 'הוספת קטגוריה', 'إضافة فئة'],
  ['No documents match “{0}”.', 'אין מסמכים שמתאימים ל„{0}”.', 'لا توجد مستندات تطابق «{0}».'],
  ['Possible duplicate', 'כפילות אפשרית', 'نسخة مكررة محتملة'],
  ['Bills', 'חשבונות', 'فواتير'],
  ['Insurance', 'ביטוח', 'تأمين'],
  ['Bank', 'בנק', 'بنك'],
  ['Government', 'ממשלה ורשויות', 'جهات حكومية'],
  ['Other', 'אחר', 'أخرى'],
  ['Unknown', 'לא ידוע', 'غير معروف'],
  ['Not detected', 'לא זוהה', 'لم يُكتشف'],
  // review
  ['Nothing left to review', 'אין מה לבדוק', 'لا شيء للمراجعة'],
  ['1 document needs your attention', 'מסמך אחד דורש את תשומת לבך', 'مستند واحد يحتاج إلى انتباهك'],
  ['{0} documents need your attention', '{0} מסמכים דורשים את תשומת לבך', '{0} مستندات تحتاج إلى انتباهك'],
  ['The other {0} were sorted without you. These were ambiguous, so the choice is yours.', 'שאר {0} המסמכים מוינו בלעדיך. אלה לא היו חד־משמעיים, אז ההחלטה שלך.', 'فُرزت المستندات الأخرى ({0}) بدونك. هذه غير واضحة، فالقرار لك.'],
  ['All {0} documents are filed. You can still change any category from a document’s page.', 'כל {0} המסמכים מתויקים. עדיין אפשר לשנות קטגוריה מדף המסמך.', 'تم حفظ جميع المستندات ({0}). لا يزال بإمكانك تغيير أي فئة من صفحة المستند.'],
  ['Two documents look very similar.', 'שני מסמכים נראים דומים מאוד.', 'مستندان متشابهان جدًا.'],
  ['First copy', 'עותק ראשון', 'النسخة الأولى'],
  ['Second copy', 'עותק שני', 'النسخة الثانية'],
  ['First copy · captured {0}', 'עותק ראשון · נקלט ב־{0}', 'النسخة الأولى · التُقطت {0}'],
  ['Second copy · captured {0}', 'עותק שני · נקלט ב־{0}', 'النسخة الثانية · التُقطت {0}'],
  ['The pages look the same, even though they were framed differently', 'הדפים נראים זהים, אף שצולמו במסגור שונה', 'الصفحات تبدو متطابقة، رغم اختلاف تأطيرها'],
  ['The text read from both mostly matches', 'הטקסט שנקרא משניהם תואם ברובו', 'النص المقروء من كليهما متطابق في معظمه'],
  ['Same date ({0})', 'אותו תאריך ({0})', 'التاريخ نفسه ({0})'],
  ['Same sender and date ({0})', 'אותו שולח ואותו תאריך ({0})', 'المرسل والتاريخ نفسهما ({0})'],
  ['Same account number', 'אותו מספר חשבון', 'رقم الحساب نفسه'],
  ['Text on both pages matches closely', 'הטקסט בשני הדפים כמעט זהה', 'النص في الصفحتين متطابق تقريبًا'],
  ['Keep both', 'לשמור את שניהם', 'الاحتفاظ بالاثنين'],
  ['Mark as duplicate', 'סימון ככפילות', 'تعليم كنسخة مكررة'],
  ['Document type unclear', 'סוג המסמך לא ברור', 'نوع المستند غير واضح'],
  ['Document type unclear.', 'סוג המסמך לא ברור.', 'نوع المستند غير واضح.'],
  ['Open document', 'פתיחת המסמך', 'فتح المستند'],
  ['Handwritten page with no letterhead.', 'דף בכתב יד ללא נייר מכתבים.', 'صفحة مكتوبة بخط اليد بلا ترويسة.'],
  ['No known sender found on this page.', 'לא נמצא שולח מוכר בדף הזה.', 'لم يُعثر على مرسل معروف في هذه الصفحة.'],
  ['No text could be read from this page.', 'לא ניתן היה לקרוא טקסט מהדף הזה.', 'تعذّرت قراءة أي نص من هذه الصفحة.'],
  ['Sender:', 'שולח:', 'المرسل:'],
  ['Date:', 'תאריך:', 'التاريخ:'],
  ['not found', 'לא נמצא', 'غير موجود'],
  ['File it under', 'לתייק תחת', 'احفظه ضمن'],
  ['New category', 'קטגוריה חדשה', 'فئة جديدة'],
  ['Not a document', 'זה לא מסמך', 'ليس مستندًا'],
  ['Leave unclassified', 'להשאיר לא מסווג', 'تركه بلا تصنيف'],
  ['Choose category', 'בחירת קטגוריה', 'اختيار فئة'],
  ['Marked as duplicate. The first copy is kept.', 'סומן ככפילות. העותק הראשון נשמר.', 'عُلِّم كنسخة مكررة. احتُفظ بالنسخة الأولى.'],
  ['Kept both copies', 'שני העותקים נשמרו', 'تم الاحتفاظ بالنسختين'],
  ['Filed under {0}', 'תויק תחת {0}', 'حُفظ ضمن {0}'],
  ['Left unclassified, filed under Other', 'נשאר לא מסווג, תויק תחת אחר', 'تُرك بلا تصنيف وحُفظ ضمن أخرى'],
  ['Deleted from this archive', 'נמחק מהארכיון', 'حُذف من هذا الأرشيف'],
  ['Review', 'לבדיקה', 'مراجعة'],
  ['Possible duplicate of another document.', 'כפילות אפשרית של מסמך אחר.', 'نسخة مكررة محتملة لمستند آخر.'],
  // document view
  ['Looks like', 'נראה כמו', 'يبدو أنه'],
  ['+ New category…', '+ קטגוריה חדשה…', '+ فئة جديدة…'],
  ['Sender', 'שולח', 'المرسل'],
  ['Date', 'תאריך', 'التاريخ'],
  ['Amount', 'סכום', 'المبلغ'],
  ['Title', 'כותרת', 'العنوان'],
  ['Low certainty', 'ודאות נמוכה', 'ثقة منخفضة'],
  ['Set by you', 'נקבע על ידך', 'حدّدته أنت'],
  ['No date found', 'לא נמצא תאריך', 'لم يُعثر على تاريخ'],
  ['No amount found', 'לא נמצא סכום', 'لم يُعثر على مبلغ'],
  ['Look again', 'לבדוק שוב', 'ابحث مجددًا'],
  ['Today, {0} · stored on this device', 'היום, {0} · שמור במכשיר הזה', 'اليوم، {0} · محفوظ على هذا الجهاز'],
  ['Edit details', 'עריכת פרטים', 'تعديل التفاصيل'],
  ['Why we classified this', 'למה סיווגנו כך', 'لماذا صنّفناه هكذا'],
  ['Extracted text', 'הטקסט שחולץ', 'النص المستخرج'],
  ['No text was read from this page.', 'לא נקרא טקסט מהדף הזה.', 'لم يُقرأ أي نص من هذه الصفحة.'],
  ['Read automatically on this device and may contain mistakes. If a detail matters, check the original page.', 'נקרא אוטומטית במכשיר הזה ועלול להכיל טעויות. אם פרט חשוב לך, בדקו את הדף המקורי.', 'قُرئ تلقائيًا على هذا الجهاز وقد يحتوي على أخطاء. إذا كان تفصيل ما مهمًا، فتحقق من الصفحة الأصلية.'],
  ['Delete document', 'מחיקת המסמך', 'حذف المستند'],
  ['Delete this document from the archive?', 'למחוק את המסמך מהארכיון?', 'حذف هذا المستند من الأرشيف؟'],
  ['View original page', 'הצגת הדף המקורי', 'عرض الصفحة الأصلية'],
  ['Original page', 'הדף המקורי', 'الصفحة الأصلية'],
  ['Original camera frame', 'תמונת המצלמה המקורית', 'لقطة الكاميرا الأصلية'],
  ['Original capture · page {0} of {1}', 'הצילום המקורי · עמוד {0} מתוך {1}', 'اللقطة الأصلية · الصفحة {0} من {1}'],
  ['The unedited camera frame, kept so you can always check what was actually on the paper.', 'תמונת המצלמה ללא עריכה, שנשמרת כדי שתמיד תוכלו לבדוק מה באמת היה כתוב בנייר.', 'لقطة الكاميرا دون تعديل، محفوظة لتتمكن دائمًا من التحقق مما كان على الورقة فعلًا.'],
  ['The unedited camera frame, with the outline that was detected, kept so you can always check what was actually on the paper.', 'תמונת המצלמה ללא עריכה, עם המסגרת שזוהתה, שנשמרת כדי שתמיד תוכלו לבדוק מה באמת היה כתוב בנייר.', 'لقطة الكاميرا دون تعديل مع الإطار الذي اكتُشف، محفوظة لتتمكن دائمًا من التحقق مما كان على الورقة فعلًا.'],
  ['Scan {0} · from the full-resolution camera photo', 'סריקה {0} · מתמונת המצלמה ברזולוציה מלאה', 'المسح {0} · من صورة الكاميرا بالدقة الكاملة'],
  ['Scan {0} · from the video picture', 'סריקה {0} · מתמונת הווידאו', 'المسح {0} · من صورة الفيديو'],
  ['Page {0}', 'עמוד {0}', 'الصفحة {0}'],
  ['Page {0} of {1}', 'עמוד {0} מתוך {1}', 'الصفحة {0} من {1}'],
  ['Earlier', 'קודם', 'إلى الأمام'],
  ['Move page earlier', 'הזזת הדף אחורה בסדר', 'نقل الصفحة إلى الأمام'],
  ['Move page later', 'הזזת הדף קדימה בסדר', 'نقل الصفحة إلى الخلف'],
  ['Retake', 'צילום מחדש', 'إعادة الالتقاط'],
  ['Move to…', 'העברה אל…', 'نقل إلى…'],
  ['Delete this page', 'מחיקת הדף', 'حذف هذه الصفحة'],
  ['Delete page {0}?', 'למחוק את עמוד {0}?', 'حذف الصفحة {0}؟'],
  ['Delete page {0} and this document?', 'למחוק את עמוד {0} ואת המסמך הזה?', 'حذف الصفحة {0} وهذا المستند؟'],
  ['Add page', 'הוספת דף', 'إضافة صفحة'],
  ['Scan more pages into this document', 'סריקת דפים נוספים למסמך הזה', 'مسح صفحات أخرى في هذا المستند'],
  ['Move page', 'העברת דף', 'نقل الصفحة'],
  ['Move this page to…', 'להעביר את הדף אל…', 'نقل هذه الصفحة إلى…'],
  ['A new document', 'מסמך חדש', 'مستند جديد'],
  ['Sorted on its own from this page’s text', 'ממוין לבד לפי הטקסט שבדף', 'يُفرز وحده حسب نص هذه الصفحة'],
  ['The page is added at the end. You can then move it earlier.', 'הדף יתווסף בסוף. אחר כך אפשר להקדים אותו.', 'تُضاف الصفحة في النهاية. ويمكنك بعدها نقلها إلى الأمام.'],
  ['Page deleted', 'הדף נמחק', 'حُذفت الصفحة'],
  ['Page moved to {0}', 'הדף הועבר אל {0}', 'نُقلت الصفحة إلى {0}'],
  ['Page retaken. Reading its text…', 'הדף צולם מחדש. קוראים את הטקסט…', 'أُعيد التقاط الصفحة. جارٍ قراءة نصها…'],
  ['New page is ready', 'הדף החדש מוכן', 'الصفحة الجديدة جاهزة'],
  ['Added {0}. Reading the text…', 'נוספו {0}. קוראים את הטקסט…', 'أُضيفت {0}. جارٍ قراءة النص…'],
  ['Pages added', 'הדפים נוספו', 'أُضيفت الصفحات'],
  // reasons (why it was sorted)
  ['Detected sender', 'שולח שזוהה', 'المرسل المكتشف'],
  ['Detected document type', 'סוג מסמך שזוהה', 'نوع المستند المكتشف'],
  ['Detected date', 'תאריך שזוהה', 'التاريخ المكتشف'],
  ['Detected amount', 'סכום שזוהה', 'المبلغ المكتشف'],
  ['Looks like sender', 'נראה כמו השולח', 'يبدو أنه المرسل'],
  ['Document type', 'סוג המסמך', 'نوع المستند'],
  ['Image', 'תמונה', 'الصورة'],
  ['Not found', 'לא נמצא', 'غير موجود'],
  ['Unclear', 'לא ברור', 'غير واضح'],
  ['May be blurry', 'ייתכן שמטושטש', 'قد تكون غير واضحة'],
  ['Filed by you', 'תויק על ידך', 'حفظته أنت'],
  ['Based on the sender', 'לפי השולח', 'بناءً على المرسل'],
  ['Letterhead reads “{0}”', 'בנייר המכתבים כתוב „{0}”', 'الترويسة تقول «{0}»'],
  ['Heading contains “{0}”', 'הכותרת מכילה „{0}”', 'العنوان يحتوي على «{0}»'],
  ['Printed next to “{0}”', 'מודפס ליד „{0}”', 'مطبوع بجانب «{0}»'],
  ['Found “{0}” in the text', 'נמצא „{0}” בטקסט', 'وُجد «{0}» في النص'],
  ['Text contains “{0}” (your rule)', 'הטקסט מכיל „{0}” (הכלל שלך)', 'النص يحتوي على «{0}» (قاعدتك)'],
  ['Text contains “{0}”', 'הטקסט מכיל „{0}”', 'النص يحتوي على «{0}»'],
  ['Number next to “{0}”', 'מספר ליד „{0}”', 'رقم بجانب «{0}»'],
  ['Handwritten “{0}”, low certainty', 'בכתב יד „{0}”, ודאות נמוכה', 'بخط اليد «{0}»، ثقة منخفضة'],
  ['Handwritten “14.02.25”, low certainty', 'בכתב יד „14.02.25”, ודאות נמוכה', 'بخط اليد «14.02.25»، ثقة منخفضة'],
  ['No letterhead or logo found', 'לא נמצאו נייר מכתבים או לוגו', 'لم يُعثر على ترويسة أو شعار'],
  ['No heading matched a known type', 'אף כותרת לא התאימה לסוג מוכר', 'لم يطابق أي عنوان نوعًا معروفًا'],
  ['No known sender name in the text', 'אין בטקסט שם שולח מוכר', 'لا يوجد اسم مرسل معروف في النص'],
  ['No text could be read from this page', 'לא ניתן היה לקרוא טקסט מהדף הזה', 'تعذّرت قراءة أي نص من هذه الصفحة'],
  ['First date found in the text', 'התאריך הראשון שנמצא בטקסט', 'أول تاريخ وُجد في النص'],
  ['No date pattern in the text', 'אין בטקסט תבנית של תאריך', 'لا يوجد نمط تاريخ في النص'],
  ['Found on a second look at the text', 'נמצא בבדיקה חוזרת של הטקסט', 'وُجد عند إعادة فحص النص'],
  ['First line of the page', 'השורה הראשונה בדף', 'السطر الأول من الصفحة'],
  ['Focus didn’t fully settle while capturing. Check the original page', 'המיקוד לא התייצב לגמרי בזמן הצילום. בדקו את הדף המקורי', 'لم يستقر التركيز تمامًا أثناء الالتقاط. تحقق من الصفحة الأصلية'],
  ['Utility layout: billing period, usage and an amount', 'מבנה של חשבון: תקופת חיוב, צריכה וסכום', 'تخطيط فاتورة خدمات: فترة الفوترة والاستهلاك والمبلغ'],
  ['Insurer name and a policy number', 'שם מבטח ומספר פוליסה', 'اسم شركة التأمين ورقم الوثيقة'],
  ['Bank or card issuer name and an account number', 'שם בנק או חברת אשראי ומספר חשבון', 'اسم البنك أو جهة إصدار البطاقة ورقم الحساب'],
  ['Government or municipal sender', 'שולח ממשלתי או עירוני', 'مرسل حكومي أو بلدي'],
  ['No stronger match, so filed under Other', 'אין התאמה טובה יותר, לכן תויק תחת אחר', 'لا يوجد تطابق أقوى، لذا حُفظ ضمن أخرى'],
  ['A store receipt. Add a category such as “Store receipts” to file these together', 'קבלה מחנות. הוסיפו קטגוריה כמו „קבלות” כדי לתייק אותן יחד', 'إيصال متجر. أضف فئة مثل «إيصالات المتاجر» لحفظها معًا'],
  ['Text mentions ארנונה (municipal tax)', 'הטקסט מזכיר ארנונה', 'النص يذكر ארנונה (ضريبة البلدية)'],
  ['Text mentions a policy or premium', 'הטקסט מזכיר פוליסה או פרמיה', 'النص يذكر وثيقة تأمين أو قسطًا'],
  ['Text looks like a bank statement', 'הטקסט נראה כמו דף חשבון', 'النص يبدو ككشف حساب بنكي'],
  ['Text mentions usage units', 'הטקסט מזכיר יחידות צריכה', 'النص يذكر وحدات استهلاك'],
  // edit / categories
  ['Name', 'שם', 'الاسم'],
  ['Add a category', 'הוספת קטגוריה', 'إضافة فئة'],
  ['New category for this document', 'קטגוריה חדשה למסמך הזה', 'فئة جديدة لهذا المستند'],
  ['Start from', 'להתחיל מ־', 'ابدأ من'],
  ['e.g. Store receipts or קבלות', 'למשל קבלות', 'مثل إيصالات المتاجر'],
  ['Words that identify it', 'מילים שמזהות אותה', 'كلمات تميّزها'],
  ['optional, separated by commas', 'לא חובה, מופרדות בפסיקים', 'اختياري، مفصولة بفواصل'],
  ['Pages whose text contains any of these words are filed here automatically, now and in future sessions.', 'דפים שהטקסט שלהם מכיל אחת מהמילים האלה יתויקו כאן אוטומטית, עכשיו ובסריקות הבאות.', 'الصفحات التي يحتوي نصها على أي من هذه الكلمات تُحفظ هنا تلقائيًا، الآن وفي الجلسات القادمة.'],
  ['Your categories', 'הקטגוריות שלך', 'فئاتك'],
  ['No words, filed by hand only', 'בלי מילים, מתויק ידנית בלבד', 'بلا كلمات، تُحفظ يدويًا فقط'],
  ['Remove {0}', 'הסרת {0}', 'إزالة {0}'],
  ['Added {0}', 'נוספה {0}', 'أُضيفت {0}'],
  ['Added {0}. Moved {1} there.', 'נוספה {0}. {1} הועברו אליה.', 'أُضيفت {0}. ونُقل إليها {1}.'],
  ['Removed {0}. Its documents moved to Other.', 'הוסרה {0}. המסמכים שלה הועברו לאחר.', 'أُزيلت {0}. ونُقلت مستنداتها إلى أخرى.'],
  ['Store receipts', 'קבלות', 'إيصالات المتاجر'],
  ['Medical', 'רפואה', 'طبي'],
  ['Car', 'רכב', 'السيارة'],
  ['Warranties', 'אחריות', 'الضمانات'],
  ['Kids & school', 'ילדים ובית ספר', 'الأطفال والمدرسة'],
  // export
  ['Export archive', 'ייצוא הארכיון', 'تصدير الأرشيف'],
  ['Everything is generated on your device. Your documents are never uploaded.', 'הכול נוצר במכשיר שלך. המסמכים שלך לעולם לא מועלים.', 'يُنشأ كل شيء على جهازك. لا تُرفع مستنداتك أبدًا.'],
  ['Download documents', 'הורדת המסמכים', 'تنزيل المستندات'],
  ['Download searchable PDF', 'הורדת PDF שאפשר לחפש בו', 'تنزيل PDF قابل للبحث'],
  ['Download metadata CSV', 'הורדת קובץ CSV של הפרטים', 'تنزيل ملف CSV للبيانات'],
  ['Download complete archive ZIP', 'הורדת הארכיון המלא כ־ZIP', 'تنزيل الأرشيف الكامل ZIP'],
  ['{0} in one ZIP, named by date and sender', '{0} בקובץ ZIP אחד, עם שמות לפי תאריך ושולח', '{0} في ملف ZIP واحد، بأسماء حسب التاريخ والمرسل'],
  ['One file, {0}, text you can search and copy', 'קובץ אחד, {0}, עם טקסט שאפשר לחפש ולהעתיק', 'ملف واحد، {0}، بنص يمكنك البحث فيه ونسخه'],
  ['Opens in Excel or Google Sheets, Hebrew included', 'נפתח ב־Excel או ב־Google Sheets, כולל עברית', 'يفتح في Excel أو Google Sheets، مع دعم العبرية'],
  ['Category / Year folders with PDFs, original photos, extracted text and index.csv', 'תיקיות קטגוריה / שנה עם קובצי PDF, תמונות מקוריות, הטקסט שחולץ ו־index.csv', 'مجلدات الفئة / السنة مع ملفات PDF والصور الأصلية والنص المستخرج وindex.csv'],
  ['Needs scanned pages. The sample documents have none.', 'נדרשים דפים סרוקים. למסמכים לדוגמה אין כאלה.', 'يتطلب صفحات ممسوحة. المستندات التجريبية لا تحتوي عليها.'],
  ['Prepare', 'הכנה', 'تجهيز'],
  ['Share…', 'שיתוף…', 'مشاركة…'],
  ['Save puts the file in your {0}. Share… lets you send it to Google Drive, WhatsApp, email or Files instead.', '„שמירה” מכניסה את הקובץ ל{0}. „שיתוף…” מאפשר לשלוח אותו ל־Google Drive, לוואטסאפ, למייל או לקבצים.', '«حفظ» يضع الملف في {0}. «مشاركة…» يتيح إرساله إلى Google Drive أو واتساب أو البريد أو الملفات.'],
  ['Saved to your {0}', 'נשמר ב{0}', 'حُفظ في {0}'],
  ['Files app › Downloads', 'אפליקציית הקבצים › הורדות', 'تطبيق الملفات › التنزيلات'],
  ['Downloads folder (Files app)', 'תיקיית ההורדות (אפליקציית הקבצים)', 'مجلد التنزيلات (تطبيق الملفات)'],
  ['Downloads folder', 'תיקיית ההורדות', 'مجلد التنزيلات'],
  ['Sharing isn’t available here. Use Save instead.', 'שיתוף לא זמין כאן. השתמשו בשמירה.', 'المشاركة غير متاحة هنا. استخدم الحفظ بدلًا منها.'],
  ['Claude’s preview blocks saving. Use the hosted site to save files.', 'התצוגה המקדימה של Claude חוסמת שמירה. השתמשו באתר עצמו כדי לשמור קבצים.', 'معاينة Claude تمنع الحفظ. استخدم الموقع نفسه لحفظ الملفات.'],
  ['Export archives', 'ייצוא ארכיונים', 'تصدير الأرشيفات'],
  ['Export to your folder', 'ייצוא לתיקייה שלך', 'التصدير إلى مجلدك'],
  ['One ZIP for several archives, with the same folders every time: Category / Year. Unzip it into the same folder (for example in Google Drive) and it merges with what\'s already there.', 'קובץ ZIP אחד לכמה ארכיונים, עם אותן תיקיות בכל פעם: קטגוריה / שנה. חלצו אותו לאותה תיקייה (למשל ב־Google Drive) והוא יתמזג עם מה שכבר נמצא שם.', 'ملف ZIP واحد لعدة أرشيفات، بالمجلدات نفسها في كل مرة: الفئة / السنة. فُكّ ضغطه في المجلد نفسه (مثلًا في Google Drive) فيندمج مع ما هو موجود.'],
  ['Archives', 'ארכיונים', 'الأرشيفات'],
  [' · not exported yet', ' · עוד לא יוצא', ' · لم يُصدَّر بعد'],
  [' · {0} new', ' · {0} חדשים', ' · {0} جديدة'],
  ['Only documents not exported before', 'רק מסמכים שעוד לא יוצאו', 'فقط المستندات التي لم تُصدَّر من قبل'],
  ['Text files next to each PDF', 'קובצי טקסט ליד כל PDF', 'ملفات نصية بجانب كل PDF'],
  ['Original camera photos', 'תמונות המצלמה המקוריות', 'صور الكاميرا الأصلية'],
  ['(larger)', '(גדול יותר)', '(أكبر حجمًا)'],
  ['index.csv always lists all {0} documents from the chosen archives, so the copy in your folder stays complete.', 'הקובץ index.csv תמיד מפרט את כל {0} המסמכים מהארכיונים שנבחרו, כך שהעותק בתיקייה שלך נשאר שלם.', 'يسرد index.csv دائمًا جميع المستندات ({0}) من الأرشيفات المختارة، فتبقى النسخة في مجلدك كاملة.'],
  ['{0} new PDFs, index of {1}', '{0} קובצי PDF חדשים, אינדקס של {1}', '{0} ملفات PDF جديدة، وفهرس من {1}'],
  ['Prepare export', 'הכנת הייצוא', 'تجهيز التصدير'],
  ['Prepare updated index', 'הכנת אינדקס מעודכן', 'تجهيز فهرس محدّث'],
  // archives list
  ['Your archives', 'הארכיונים שלך', 'أرشيفاتك'],
  ['Saved on this device', 'נשמר במכשיר הזה', 'محفوظ على هذا الجهاز'],
  ['New archive', 'ארכיון חדש', 'أرشيف جديد'],
  ['Archive', 'ארכיון', 'أرشيف'],
  ['Archive name', 'שם הארכיון', 'اسم الأرشيف'],
  ['Rename', 'שינוי שם', 'إعادة تسمية'],
  [' · {0} to review', ' · {0} לבדיקה', ' · {0} للمراجعة'],
  ['{0} not sorted yet', '{0} עוד לא מוינו', '{0} لم تُفرز بعد'],
  ['Last changed', 'שינוי אחרון', 'آخر تغيير'],
  ['Delete this archive and its {0}?', 'למחוק את הארכיון הזה ואת {0}?', 'حذف هذا الأرشيف و{0}؟'],
  ['Continue capturing', 'המשך סריקה', 'متابعة الالتقاط'],
  ['Finish and sort', 'סיום ומיון', 'إنهاء وفرز'],
  ['Add pages', 'הוספת דפים', 'إضافة صفحات'],
  ['Delete {0}', 'מחיקת {0}', 'حذف {0}'],
  ['1 document isn’t exported yet.', 'מסמך אחד עוד לא יוצא.', 'مستند واحد لم يُصدَّر بعد.'],
  ['{0} documents aren’t exported yet.', '{0} מסמכים עוד לא יוצאו.', '{0} مستندات لم تُصدَّر بعد.'],
  ['They live only in this browser. Export to keep your own copy.', 'הם נמצאים רק בדפדפן הזה. ייצאו כדי לשמור עותק משלכם.', 'إنها موجودة فقط في هذا المتصفح. صدّرها للاحتفاظ بنسختك الخاصة.'],
  ['Archive deleted from this device', 'הארכיון נמחק מהמכשיר', 'حُذف الأرشيف من هذا الجهاز'],
  ['That archive is no longer on this device.', 'הארכיון הזה כבר לא נמצא במכשיר.', 'هذا الأرشيف لم يعد على هذا الجهاز.'],
  ['This browser won’t keep archives, so this one lasts until you close the page.', 'הדפדפן הזה לא שומר ארכיונים, לכן הארכיון יישאר רק עד שתסגרו את הדף.', 'هذا المتصفح لا يحتفظ بالأرشيفات، لذا يبقى هذا الأرشيف حتى تغلق الصفحة.'],
  ['Started over. Place the first document.', 'התחלנו מחדש. הניחו את המסמך הראשון.', 'بدأنا من جديد. ضع المستند الأول.'],
  // privacy
  ['Your documents stay on this device.', 'המסמכים שלך נשארים במכשיר הזה.', 'تبقى مستنداتك على هذا الجهاز.'],
  ['Camera frames are analyzed in this browser.', 'תמונות המצלמה מנותחות בדפדפן הזה.', 'تُحلَّل لقطات الكاميرا في هذا المتصفح.'],
  ['Page images and extracted text are stored only here.', 'תמונות הדפים והטקסט שחולץ נשמרים רק כאן.', 'تُحفظ صور الصفحات والنص المستخرج هنا فقط.'],
  ['No account and no sign-in. There is nothing to upload to.', 'אין חשבון ואין התחברות. אין לאן להעלות.', 'لا حساب ولا تسجيل دخول. لا يوجد مكان للرفع إليه.'],
  ['Exports are built on the device, even offline.', 'קובצי הייצוא נוצרים במכשיר, גם בלי אינטרנט.', 'تُنشأ ملفات التصدير على الجهاز، حتى دون اتصال.'],
  ['The text reader is downloaded once from a public library server. Your pages are never sent anywhere.', 'קורא הטקסט יורד פעם אחת משרת ספריות ציבורי. הדפים שלך לעולם לא נשלחים לשום מקום.', 'يُنزَّل قارئ النص مرة واحدة من خادم مكتبات عام. لا تُرسل صفحاتك إلى أي مكان أبدًا.'],
  ['Delete all archives from this device', 'מחיקת כל הארכיונים מהמכשיר', 'حذف كل الأرشيفات من هذا الجهاز'],
  ['Delete every archive, page and text on this device? This can’t be undone.', 'למחוק את כל הארכיונים, הדפים והטקסטים במכשיר? אי אפשר לבטל את זה.', 'حذف كل الأرشيفات والصفحات والنصوص على هذا الجهاز؟ لا يمكن التراجع عن ذلك.'],
  // camera errors
  ['The camera only works on an https:// address.', 'המצלמה עובדת רק בכתובת https://.', 'تعمل الكاميرا فقط على عنوان https://.'],
  ['This browser doesn’t allow camera access here. Open the page directly in Safari or Chrome.', 'הדפדפן הזה לא מאפשר גישה למצלמה כאן. פתחו את הדף ישירות ב־Safari או ב־Chrome.', 'هذا المتصفح لا يسمح بالوصول إلى الكاميرا هنا. افتح الصفحة مباشرة في Safari أو Chrome.'],
  ['Claude’s viewer blocks the camera. Open a hosted copy of this page to use it.', 'התצוגה של Claude חוסמת את המצלמה. פתחו עותק מתארח של הדף כדי להשתמש בה.', 'عارض Claude يحجب الكاميرا. افتح نسخة مستضافة من الصفحة لاستخدامها.'],
  ['Camera access was declined. Allow it in your browser’s site settings, then try again.', 'הגישה למצלמה נדחתה. אשרו אותה בהגדרות האתר בדפדפן ונסו שוב.', 'رُفض الوصول إلى الكاميرا. اسمح به في إعدادات الموقع في المتصفح ثم حاول مجددًا.'],
  ['No camera was found on this device.', 'לא נמצאה מצלמה במכשיר הזה.', 'لم يُعثر على كاميرا في هذا الجهاز.'],
  ['Another app is using the camera. Close it and try again.', 'אפליקציה אחרת משתמשת במצלמה. סגרו אותה ונסו שוב.', 'تطبيق آخر يستخدم الكاميرا. أغلقه وحاول مجددًا.'],
  ['The camera couldn’t start ({0}).', 'לא ניתן היה להפעיל את המצלמה ({0}).', 'تعذّر تشغيل الكاميرا ({0}).'],
  ['No date', 'ללא תאריך', 'بلا تاريخ'],
];

const DICT: Record<string, Record<string, string>> = { he: {}, ar: {} };
TR.forEach(([en, he, ar]) => { DICT.he[en] = he; DICT.ar[en] = ar; });

/* Counted words. Hebrew: one / two / other. Arabic: zero / one / two / few (3–10) / many (11–99) / other. */
const PLURALS: Record<string, Record<string, Record<string, string>>> = {
  he: {
    document: { one: 'מסמך אחד', two: '2 מסמכים', other: '{n} מסמכים' },
    page: { one: 'עמוד אחד', two: '2 עמודים', other: '{n} עמודים' },
    category: { one: 'קטגוריה אחת', two: '2 קטגוריות', other: '{n} קטגוריות' },
    'possible duplicate': { one: 'כפילות אפשרית אחת', two: '2 כפילויות אפשריות', other: '{n} כפילויות אפשריות' },
    PDF: { one: 'קובץ PDF אחד', two: '2 קובצי PDF', other: '{n} קובצי PDF' },
    'new PDF': { one: 'קובץ PDF חדש אחד', two: '2 קובצי PDF חדשים', other: '{n} קובצי PDF חדשים' },
  },
  ar: {
    document: { zero: 'لا مستندات', one: 'مستند واحد', two: 'مستندان', few: '{n} مستندات', many: '{n} مستندًا', other: '{n} مستند' },
    page: { zero: 'لا صفحات', one: 'صفحة واحدة', two: 'صفحتان', few: '{n} صفحات', many: '{n} صفحة', other: '{n} صفحة' },
    category: { zero: 'لا فئات', one: 'فئة واحدة', two: 'فئتان', few: '{n} فئات', many: '{n} فئة', other: '{n} فئة' },
    'possible duplicate': { zero: 'لا نسخ مكررة محتملة', one: 'نسخة مكررة محتملة', two: 'نسختان مكررتان محتملتان', few: '{n} نسخ مكررة محتملة', many: '{n} نسخة مكررة محتملة', other: '{n} نسخة مكررة محتملة' },
    PDF: { zero: 'لا ملفات PDF', one: 'ملف PDF واحد', two: 'ملفا PDF', few: '{n} ملفات PDF', many: '{n} ملف PDF', other: '{n} ملف PDF' },
    'new PDF': { zero: 'لا ملفات PDF جديدة', one: 'ملف PDF جديد', two: 'ملفا PDF جديدان', few: '{n} ملفات PDF جديدة', many: '{n} ملف PDF جديدًا', other: '{n} ملف PDF جديد' },
  },
};
